org.apache.zeppelin.notebook.Note$1.run : r1 = $r4 >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r5 = staticinvoke <org.apache.zeppelin.notebook.Note: org.slf4j.Logger access$000()>()
org.apache.zeppelin.notebook.Note$1.run : $r5 = staticinvoke <org.apache.zeppelin.notebook.Note: org.slf4j.Logger access$000()>() >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r6 = virtualinvoke r1.<java.io.IOException: java.lang.String getMessage()>()
org.apache.zeppelin.notebook.Note$1.run : $r6 = virtualinvoke r1.<java.io.IOException: java.lang.String getMessage()>() >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : interfaceinvoke $r5.<org.slf4j.Logger: void error(java.lang.String,java.lang.Throwable)>($r6, r1)
org.apache.zeppelin.notebook.Note$1.run : interfaceinvoke $r5.<org.slf4j.Logger: void error(java.lang.String,java.lang.Throwable)>($r6, r1) >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : return
org.apache.zeppelin.notebook.Note$1.run : $r2 = r0.<org.apache.zeppelin.notebook.Note$1: org.apache.zeppelin.notebook.Note this$0> >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r3 = r0.<org.apache.zeppelin.notebook.Note$1: org.apache.zeppelin.user.AuthenticationInfo val$subject>
org.apache.zeppelin.notebook.Note$1.run : $r2 = r0.<org.apache.zeppelin.notebook.Note$1: org.apache.zeppelin.notebook.Note this$0> >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r4 := @caughtexception
org.apache.zeppelin.notebook.Note$1.run : $r3 = r0.<org.apache.zeppelin.notebook.Note$1: org.apache.zeppelin.user.AuthenticationInfo val$subject> >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : virtualinvoke $r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r3)
org.apache.zeppelin.notebook.Note$1.run : $r3 = r0.<org.apache.zeppelin.notebook.Note$1: org.apache.zeppelin.user.AuthenticationInfo val$subject> >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r4 := @caughtexception
org.apache.zeppelin.notebook.Note$1.run : virtualinvoke $r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r3) >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : goto [?= return]
org.apache.zeppelin.notebook.Note$1.run : virtualinvoke $r2.<org.apache.zeppelin.notebook.Note: void persist(org.apache.zeppelin.user.AuthenticationInfo)>($r3) >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : $r4 := @caughtexception
org.apache.zeppelin.notebook.Note$1.run : goto [?= return] >>>>>>>> org.apache.zeppelin.notebook.Note$1.run : return
