org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r3 = r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : entermonitor r1
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : entermonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : entermonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r9 = $r32 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r9 = $r32 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw r9
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED>
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r10 == $r11
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r10 == $r11 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r10 == $r11 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph>
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r10 == $r11 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = virtualinvoke $r17.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getCurrentRepl()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = virtualinvoke $r17.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getCurrentRepl()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r5 != null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = virtualinvoke $r17.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getCurrentRepl()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r5 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r5 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = virtualinvoke r5.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r5 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = virtualinvoke r5.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r6 = virtualinvoke $r19.<org.apache.zeppelin.interpreter.InterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = virtualinvoke r5.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r6 = virtualinvoke $r19.<org.apache.zeppelin.interpreter.InterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r6 != null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r6 = virtualinvoke $r19.<org.apache.zeppelin.interpreter.InterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r6 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r6 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : n0 = null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r6 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : n0 = null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : n0 = null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r22 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : n0 = null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client getClient()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client getClient()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client getClient()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r22 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client getClient()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: java.lang.String getId()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r25 = virtualinvoke r21.<org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client: org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult runApplication(java.lang.String)>($r24)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r25 = virtualinvoke r21.<org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client: org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult runApplication(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r25 = virtualinvoke r21.<org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client: org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult runApplication(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r25 = virtualinvoke r21.<org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client: org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult runApplication(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r25 = virtualinvoke r21.<org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client: org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult runApplication(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= (branch)]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r26 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r26 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r26 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r26 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r26 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r27 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r27 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r27 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r27 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r27 = virtualinvoke r25.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r26.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r27)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r26.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r27) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r26.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r27) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r26.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r27) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r26.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r27) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r26
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r26 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r26 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r26 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r8 = $r31 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r8 = $r31 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r8 = $r31 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw r8
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw r8 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw r8
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r29 = $r28 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseBrokenClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r29 = $r28 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseBrokenClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseBrokenClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r30 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r21 = null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r30 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r30.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r29)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r30 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r30.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r29) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r30
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r30.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r29) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r30 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= (branch)] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= (branch)] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r28 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= (branch)] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r31 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= (branch)] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r21 == null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= return]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= return] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : return
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r3]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : virtualinvoke r6.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: void releaseClient(org.apache.zeppelin.interpreter.thrift.RemoteInterpreterService$Client)>(r21) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r3] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r3
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r3] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r7 = $r22 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r7 = $r22 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r23.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r7)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r23.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r7) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r23
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r23.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.Exception)>(r7) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r23 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r20
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r20 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r18
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r18 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r4 = new java.lang.StringBuilder
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r4 = new java.lang.StringBuilder >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r4.<java.lang.StringBuilder: void <init>()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r4 = new java.lang.StringBuilder >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r4.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r4.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = virtualinvoke $r4.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = virtualinvoke $r13.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r14)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = virtualinvoke $r13.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r14) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = virtualinvoke $r13.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r14) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r12.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r12.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r12
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r12.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r12 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r32 := @caughtexception
