org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : entermonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r8 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : entermonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r25
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r8 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r9 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED>
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r8 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r9 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r8 == $r9
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r9 = <org.apache.zeppelin.notebook.ApplicationState$Status: org.apache.zeppelin.notebook.ApplicationState$Status LOADED> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r8 == $r9 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r8 == $r9 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph>
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $r8 == $r9 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r3 = virtualinvoke $r10.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getBindedInterpreter()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r10 = r0.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication: org.apache.zeppelin.notebook.Paragraph paragraph> >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r3 = virtualinvoke $r10.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getBindedInterpreter()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r3 != null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r3 = virtualinvoke $r10.<org.apache.zeppelin.notebook.Paragraph: org.apache.zeppelin.interpreter.Interpreter getBindedInterpreter()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r3 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r3 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = virtualinvoke r3.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r3 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = virtualinvoke r3.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = (org.apache.zeppelin.interpreter.ManagedInterpreterGroup) $r11
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r11 = virtualinvoke r3.<org.apache.zeppelin.interpreter.Interpreter: org.apache.zeppelin.interpreter.InterpreterGroup getInterpreterGroup()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = (org.apache.zeppelin.interpreter.ManagedInterpreterGroup) $r11 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r4 = virtualinvoke $r12.<org.apache.zeppelin.interpreter.ManagedInterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r12 = (org.apache.zeppelin.interpreter.ManagedInterpreterGroup) $r11 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r4 = virtualinvoke $r12.<org.apache.zeppelin.interpreter.ManagedInterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r4 != null
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r4 = virtualinvoke $r12.<org.apache.zeppelin.interpreter.ManagedInterpreterGroup: org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess getRemoteInterpreterProcess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r4 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r4 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = new org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if r4 != null >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = new org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r13.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1: void <init>(org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication,org.apache.zeppelin.notebook.ApplicationState)>(r0, r1)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r13 = new org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r13.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1: void <init>(org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication,org.apache.zeppelin.notebook.ApplicationState)>(r0, r1) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r4.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: java.lang.Object callRemoteFunction(org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess$RemoteFunction)>($r13)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r13.<org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication$1: void <init>(org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication,org.apache.zeppelin.notebook.ApplicationState)>(r0, r1) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r4.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: java.lang.Object callRemoteFunction(org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess$RemoteFunction)>($r13) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = (org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult) $r14
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r14 = virtualinvoke r4.<org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess: java.lang.Object callRemoteFunction(org.apache.zeppelin.interpreter.remote.RemoteInterpreterProcess$RemoteFunction)>($r13) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = (org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult) $r14 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : r5 = (org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult) $r14 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $z0 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: boolean isSuccess()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r1]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = new org.apache.zeppelin.helium.ApplicationException
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : if $z0 == 0 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r15 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r15.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r16 = virtualinvoke r5.<org.apache.zeppelin.interpreter.thrift.RemoteApplicationResult: java.lang.String getMsg()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r15.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r15
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r15.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r16) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r15 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r1] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r1
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= exitmonitor r1] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= return]
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : exitmonitor r1 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : goto [?= return] >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : return
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r17.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r17 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r17.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r17
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r17.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("Target interpreter process is not running") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r17 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r18 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r18
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r18.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>("No interpreter found") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r18 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new java.lang.StringBuilder
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r19 = new org.apache.zeppelin.helium.ApplicationException >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new java.lang.StringBuilder >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<java.lang.StringBuilder: void <init>()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r20 = new java.lang.StringBuilder >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r21 = virtualinvoke $r20.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ")
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r20.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r21 = virtualinvoke $r20.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r22 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r21 = virtualinvoke $r20.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Can\'t run application status ") >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r22 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r22)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r22 = virtualinvoke r1.<org.apache.zeppelin.notebook.ApplicationState: org.apache.zeppelin.notebook.ApplicationState$Status getStatus()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r22) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r23 = virtualinvoke $r21.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.Object)>($r22) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r19.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r24)
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r19.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r19
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : specialinvoke $r19.<org.apache.zeppelin.helium.ApplicationException: void <init>(java.lang.String)>($r24) >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : throw $r19 >>>>>>>> org.apache.zeppelin.helium.HeliumApplicationFactory$RunApplication.run : $r25 := @caughtexception
