org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r40 = $r39 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r41 = new org.apache.xml.security.utils.resolver.ResourceResolverException
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r41 = new org.apache.xml.security.utils.resolver.ResourceResolverException >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r41.<org.apache.xml.security.utils.resolver.ResourceResolverException: void <init>(java.lang.String,java.lang.Exception,org.w3c.dom.Attr,java.lang.String)>("generic.EmptyMessage", r40, r1, r2)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r41.<org.apache.xml.security.utils.resolver.ResourceResolverException: void <init>(java.lang.String,java.lang.Exception,org.w3c.dom.Attr,java.lang.String)>("generic.EmptyMessage", r40, r1, r2) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : throw $r41
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r3 = interfaceinvoke r1.<org.w3c.dom.Attr: java.lang.String getNodeValue()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r9 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap>
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r3 = interfaceinvoke r1.<org.w3c.dom.Attr: java.lang.String getNodeValue()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r9 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $z0 = interfaceinvoke $r9.<java.util.Map: boolean containsKey(java.lang.Object)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r9 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $z0 = interfaceinvoke $r9.<java.util.Map: boolean containsKey(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : if $z0 == 0
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $z0 = interfaceinvoke $r9.<java.util.Map: boolean containsKey(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : if $z0 == 0 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r11 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap>
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : if $z0 == 0 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32 = newarray (java.lang.Object)[1]
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : if $z0 == 0 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32 = newarray (java.lang.Object)[1] >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r7 = new java.lang.StringBuilder
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32 = newarray (java.lang.Object)[1] >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r7 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r7.<java.lang.StringBuilder: void <init>()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r7 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r7.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r33 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("The URI ")
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r7.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r33 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("The URI ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r34 = virtualinvoke $r33.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r33 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("The URI ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r34 = virtualinvoke $r33.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r35 = virtualinvoke $r34.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" is not configured for offline work")
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r34 = virtualinvoke $r33.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r35 = virtualinvoke $r34.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" is not configured for offline work") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r36 = virtualinvoke $r35.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r35 = virtualinvoke $r34.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" is not configured for offline work") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r36 = virtualinvoke $r35.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32[0] = $r36
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r36 = virtualinvoke $r35.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32[0] = $r36 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r37 = $r32
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r32[0] = $r36 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r37 = $r32 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r38 = new org.apache.xml.security.utils.resolver.ResourceResolverException
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r37 = $r32 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r38 = new org.apache.xml.security.utils.resolver.ResourceResolverException >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r38.<org.apache.xml.security.utils.resolver.ResourceResolverException: void <init>(java.lang.String,java.lang.Object[],org.w3c.dom.Attr,java.lang.String)>("generic.EmptyMessage", r37, r1, r2)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r38 = new org.apache.xml.security.utils.resolver.ResourceResolverException >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r38.<org.apache.xml.security.utils.resolver.ResourceResolverException: void <init>(java.lang.String,java.lang.Object[],org.w3c.dom.Attr,java.lang.String)>("generic.EmptyMessage", r37, r1, r2) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : throw $r38
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r38.<org.apache.xml.security.utils.resolver.ResourceResolverException: void <init>(java.lang.String,java.lang.Object[],org.w3c.dom.Attr,java.lang.String)>("generic.EmptyMessage", r37, r1, r2) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : throw $r38 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r11 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r12 = interfaceinvoke $r11.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r11 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _uriMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r12 = interfaceinvoke $r11.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r4 = (java.lang.String) $r12
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r12 = interfaceinvoke $r11.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r4 = (java.lang.String) $r12 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r13 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat>
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r4 = (java.lang.String) $r12 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r13 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r14 = new java.lang.StringBuilder
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r13 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r14 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r14.<java.lang.StringBuilder: void <init>()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r14 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r14.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r15 = virtualinvoke $r14.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Mapped ")
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r14.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r15 = virtualinvoke $r14.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Mapped ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r15 = virtualinvoke $r14.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Mapped ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" to ")
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r16 = virtualinvoke $r15.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" to ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r17 = virtualinvoke $r16.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(" to ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r19 = virtualinvoke $r18.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r18 = virtualinvoke $r17.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r19 = virtualinvoke $r18.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r13.<org.apache.log4j.Category: void debug(java.lang.Object)>($r19)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r19 = virtualinvoke $r18.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r13.<org.apache.log4j.Category: void debug(java.lang.Object)>($r19) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r20 = new java.io.FileInputStream
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r13.<org.apache.log4j.Category: void debug(java.lang.Object)>($r19) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r20 = new java.io.FileInputStream >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r20.<java.io.FileInputStream: void <init>(java.lang.String)>(r4)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r20 = new java.io.FileInputStream >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r20.<java.io.FileInputStream: void <init>(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r5 = $r20
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r20.<java.io.FileInputStream: void <init>(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r5 = $r20 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r21 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat>
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r5 = $r20 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r21 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r22 = new java.lang.StringBuilder
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r21 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r22 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r22.<java.lang.StringBuilder: void <init>()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r22 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r22.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Available bytes = ")
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r22.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Available bytes = ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $i0 = virtualinvoke r5.<java.io.InputStream: int available()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r23 = virtualinvoke $r22.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Available bytes = ") >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $i0 = virtualinvoke r5.<java.io.InputStream: int available()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i0)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $i0 = virtualinvoke r5.<java.io.InputStream: int available()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i0) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r25 = virtualinvoke $r24.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r24 = virtualinvoke $r23.<java.lang.StringBuilder: java.lang.StringBuilder append(int)>($i0) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r25 = virtualinvoke $r24.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r21.<org.apache.log4j.Category: void debug(java.lang.Object)>($r25)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r25 = virtualinvoke $r24.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r21.<org.apache.log4j.Category: void debug(java.lang.Object)>($r25) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r26 = new org.apache.xml.security.signature.XMLSignatureInput
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke $r21.<org.apache.log4j.Category: void debug(java.lang.Object)>($r25) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r26 = new org.apache.xml.security.signature.XMLSignatureInput >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r26.<org.apache.xml.security.signature.XMLSignatureInput: void <init>(java.io.InputStream)>(r5)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r26 = new org.apache.xml.security.signature.XMLSignatureInput >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r26.<org.apache.xml.security.signature.XMLSignatureInput: void <init>(java.io.InputStream)>(r5) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r6 = $r26
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : specialinvoke $r26.<org.apache.xml.security.signature.XMLSignatureInput: void <init>(java.io.InputStream)>(r5) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r6 = $r26 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setSourceURI(java.lang.String)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : r6 = $r26 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setSourceURI(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r28 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _mimeMap>
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setSourceURI(java.lang.String)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r28 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _mimeMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r29 = interfaceinvoke $r28.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r28 = <org.apache.xml.security.test.utils.resolver.OfflineResolver: java.util.Map _mimeMap> >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r29 = interfaceinvoke $r28.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r30 = (java.lang.String) $r29
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r29 = interfaceinvoke $r28.<java.util.Map: java.lang.Object get(java.lang.Object)>(r3) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r30 = (java.lang.String) $r29 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setMIMEType(java.lang.String)>($r30)
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r30 = (java.lang.String) $r29 >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setMIMEType(java.lang.String)>($r30) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : return r6
org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : virtualinvoke r6.<org.apache.xml.security.signature.XMLSignatureInput: void setMIMEType(java.lang.String)>($r30) >>>>>>>> org.apache.xml.security.test.utils.resolver.OfflineResolver.engineResolve : $r39 := @caughtexception
