org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $z0 = r0.<org.apache.xml.security.test.resource.TestVectorResolver: boolean _firstEntityResolved> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $z0 = r0.<org.apache.xml.security.test.resource.TestVectorResolver: boolean _firstEntityResolved> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $z0 = r0.<org.apache.xml.security.test.resource.TestVectorResolver: boolean _firstEntityResolved> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : if $z0 != 0
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : if $z0 != 0 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: void set1stSystemId(java.lang.String)>(r2)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : if $z0 != 0 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r4 = specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: java.lang.String getFileName(java.lang.String)>(r2)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : if $z0 != 0 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : if $z0 != 0 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r17 = $r16 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : return null
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r3 = $r15 >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : return null
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r4 = specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: java.lang.String getFileName(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r4 = specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: java.lang.String getFileName(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r4 = specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: java.lang.String getFileName(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r5 = <org.apache.xml.security.test.resource.TestVectorResolver: org.apache.log4j.Category cat>
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r5 = <org.apache.xml.security.test.resource.TestVectorResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r5 = <org.apache.xml.security.test.resource.TestVectorResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r5 = <org.apache.xml.security.test.resource.TestVectorResolver: org.apache.log4j.Category cat> >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r6 = new java.lang.StringBuilder
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r6 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r6 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r6 = new java.lang.StringBuilder >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r6.<java.lang.StringBuilder: void <init>()>()
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r6.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r6.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r6.<java.lang.StringBuilder: void <init>()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r7 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("publicId=\"")
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r7 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("publicId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r7 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("publicId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r7 = virtualinvoke $r6.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("publicId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r1)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r1) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r1) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r8 = virtualinvoke $r7.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r1) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\" systemId=\"")
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\" systemId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\" systemId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r9 = virtualinvoke $r8.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\" systemId=\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r10 = virtualinvoke $r9.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\"")
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r11 = virtualinvoke $r10.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("\"") >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>()
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r12 = virtualinvoke $r11.<java.lang.StringBuilder: java.lang.String toString()>() >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : virtualinvoke $r5.<org.apache.log4j.Category: void debug(java.lang.Object)>($r12)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : virtualinvoke $r5.<org.apache.log4j.Category: void debug(java.lang.Object)>($r12) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : virtualinvoke $r5.<org.apache.log4j.Category: void debug(java.lang.Object)>($r12) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : virtualinvoke $r5.<org.apache.log4j.Category: void debug(java.lang.Object)>($r12) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r13 = new org.xml.sax.InputSource
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r13 = new org.xml.sax.InputSource >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r13 = new org.xml.sax.InputSource >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r13 = new org.xml.sax.InputSource >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r14 = new java.io.FileInputStream
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r14 = new java.io.FileInputStream >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r14 = new java.io.FileInputStream >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r14 = new java.io.FileInputStream >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r14.<java.io.FileInputStream: void <init>(java.lang.String)>(r4)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r14.<java.io.FileInputStream: void <init>(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r14.<java.io.FileInputStream: void <init>(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r14.<java.io.FileInputStream: void <init>(java.lang.String)>(r4) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r13.<org.xml.sax.InputSource: void <init>(java.io.InputStream)>($r14)
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r13.<org.xml.sax.InputSource: void <init>(java.io.InputStream)>($r14) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r13.<org.xml.sax.InputSource: void <init>(java.io.InputStream)>($r14) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke $r13.<org.xml.sax.InputSource: void <init>(java.io.InputStream)>($r14) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : return $r13
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: void set1stSystemId(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r15 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: void set1stSystemId(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : $r16 := @caughtexception
org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: void set1stSystemId(java.lang.String)>(r2) >>>>>>>> org.apache.xml.security.test.resource.TestVectorResolver.resolveEntity : r4 = specialinvoke r0.<org.apache.xml.security.test.resource.TestVectorResolver: java.lang.String getFileName(java.lang.String)>(r2)
