Test: edu.washington.cs.dt.impact.ExampleDT.CalculatorTestCase1.getSumTest
Intended behavior: FAILURE
when executed after: [edu.washington.cs.dt.impact.ExampleDT.CalculatorTestCase1.getSubTest]
The revealed different behavior: PASS
when executed after: []

